name: shutdown
description: Prioritized events for graceful shutdown in server Dart applications.
version: 0.4.4
homepage: https://github.com/isoos/shutdown

environment:
  sdk: '^3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  lints: ^4.0.0
