name: shutdown
description: Prioritized events for graceful shutdown in server Dart applications.
version: 0.2.0
homepage: https://github.com/isoos/shutdown
author: Istvan Soos <istvan.soos@gmail.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

#dependencies:
#  path: ^1.4.1

#dev_dependencies:
#  test: ^0.12.30
