name: shutdown
description: Prioritized events for graceful shutdown in server Dart applications.
version: 0.4.3
homepage: https://github.com/isoos/shutdown

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
